version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.6-buster
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install --upgrade pip
            pip install -e '.[dev]'
      - run:
          name: Run lint
          command: |
            . env/bin/activate
            pytest --pycodestyle --junitxml=reports/pycodestyle-output.xml
      - store_test_results:
          path: reports/pycodestyle-output.xml
      - store_artifacts:
          path: reports/pycodestyle-output.xml

workflows:
  version: 2

  check:
    jobs:
      - lint:
          filters:
            branches:
              ignore: master
